sadcollect/app/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("collect/", include("collect.urls")),
    path("viewer/", include("viewer.urls")),
    path("users/", include("users.urls")),
    path("", RedirectView.as_view(url="collect/", permanent=True)),
    path("select2/", include("django_select2.urls")),
    re_path(r"^celery-progress/", include("celery_progress.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sadcollect/collect/urls.py
from django.urls import path, re_path, include
from rest_framework import routers
import collect.views as views

app_name = "collect"
router = routers.SimpleRouter()
router.register(r"collection", views.TwitterCollectViewSet, basename="collection")
router.register(r"run", views.DataCollectionRunViewSet, basename="run")

urlpatterns = [
    path("", views.home, name="home"),
    path("create/", views.CollectCreateView.as_view(), name="create_collect"),
    path("update/<int:pk>", views.CollectUpdateView.as_view(), name="update_collect"),
    path("delete/<int:pk>", views.CollectDeleteView.as_view(), name="delete_collect"),
    path("start-collect/<int:collect_id>", views.start_collect, name="start_collect"),
    path("initial-nodes/<int:collect_id>/", views.home_nodes, name="collect_start_nodes"),
    path(
        "initial-nodes/<int:collect_id>/search/<str:hashtag>",
        views.home_nodes,
        name="collect_start_nodes",
    ),
    path(
        "initial-nodes/<int:collect_id>/add",
        views.NodeCreateView.as_view(),
        name="add_node",
    ),
    path(
        "initial-nodes/<int:collect_id>/add-multi/<str:hashtag>",
        views.nodes_multi_add,
        name="nodes_multi_add",
    ),
    path(
        "initial-nodes/<int:collect_id>/delete/<int:pk>",
        views.NodeDeleteView.as_view(),
        name="delete_node",
    ),
    path(
        "initial-nodes/<int:collect_id>/update/<int:pk>",
        views.NodeUpdateView.as_view(),
        name="update_node",
    ),
    path(
        "blacklist-nodes/<int:collect_id>",
        views.blacklist_nodes,
        name="blacklist_nodes",
    ),
    path(
        "blacklist-nodes/<int:collect_id>/add",
        views.BlacklistCreateView.as_view(),
        name="add_blacklist_node",
    ),
    path(
        "blacklist-nodes/<int:collect_id>/delete/<int:pk>",
        views.BlacklistDeleteView.as_view(),
        name="delete_blacklist_node",
    ),
    path(
        "blacklist-nodes/<int:collect_id>/update/<int:pk>",
        views.BlacklistUpdateView.as_view(),
        name="update_blacklist_node",
    ),
    path("<int:collect_id>/", views.list_runs, name="list_runs"),
    path(
        "<int:collect_id>/<uuid:collect_run_id>/",
        views.detail_collect_run,
        name="detail_collect_run",
    ),
    path(
        "<int:collect_id>/delete/<uuid:collect_run_id>/",
        views.RunDeleteView.as_view(),
        name="delete_run",
    ),
    path("log/<uuid:collect_run_id>", views.run_log, name="run_log"),
    path(
        "<int:collect_id>/annotate/<uuid:collect_run_id>",
        views.AnnotateRunView.as_view(),
        name="annotate_run",
    ),
    path(
        "<int:collect_id>/rename/<uuid:collect_run_id>",
        views.RenameRunView.as_view(),
        name="rename_run",
    ),
    path("hashtag/<str:hashtag>", views.display_hashtag, name="display_hashtag"),
    re_path(
        r"^collect-progress/(?P<task_id>[\w-]+)/$",
        views.get_progress,
        name="task_status",
    ),
    path("api/", include((router.urls, "collect"))),
]

sadcollect/viewer/urls.py
from django.urls import path
from . import views

app_name = "viewer"
urlpatterns = [
    path("", views.home, name="home"),
    path(
        "graph-layout-data/<uuid:collect_run_id>",
        views.get_graph_data_layout,
        name="get_graph_data_layout",
    ),
    path("display-graph/<uuid:collect_run_id>", views.display_graph, name="display_graph"),
    path("export-gexf/<uuid:collect_run_id>", views.export_gexf, name="export_gexf"),
    path("graph-gexf/<uuid:collect_run_id>", views.get_graph_gexf, name="graph_gexf"),
    path(
        "hashtags-timeline/<uuid:collect_run_id>",
        views.hashtags_timeline,
        name="hashtags_timeline",
    ),
    path(
        "hashtags-timeline/<uuid:collect_run_id>/<int:max_days>",
        views.hashtags_timeline,
        name="hashtags_timeline",
    ),
    path(
        "hashtags-timeline/<uuid:collect_run_id>/<int:max_days>/<int:resampling_step_hours>",
        views.hashtags_timeline,
        name="hashtags_timeline",
    ),
]

sadcollect/collect/models.py
import json
import uuid
from django.db import models
from polymorphic.models import PolymorphicModel
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone
from django.contrib.auth.models import User


class DataCollection(PolymorphicModel):
    COLLECTION_SOURCE_CHOICE = [("twitter", "Twitter"), ("reddit", "Reddit")]

    COLLECT_TYPE_CHOICES = [("edges", (("coreball", "Coreball"), ("fireball", "Fireball")))]

    name = models.CharField(help_text="Name", max_length=250)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    source = models.CharField(
        max_length=25,
        default="twitter",
        choices=COLLECTION_SOURCE_CHOICE,
        help_text="Collection source",
    )
    depth = models.IntegerField(
        help_text="Number of exploration steps.",
        default=2,
        validators=[MinValueValidator(2), MaxValueValidator(10)],
    )
    sampling_probability = models.IntegerField(
        help_text="Percentage of nodes randomly selected at each layer",
        default=10,
        validators=[MinValueValidator(1), MaxValueValidator(100)],
    )
    max_nodes_per_hop = models.IntegerField(
        help_text="Max number of new nodes at each hop",
        default=1000,
        validators=[MinValueValidator(1), MaxValueValidator(10000)],
    )
    collect_by = models.CharField(
        help_text="Collect by",
        choices=COLLECT_TYPE_CHOICES,
        max_length=25,
        default="coreball",
    )

    # Graph parameters
    minimum_weight = models.IntegerField(
        help_text="Minimum number of RT/mentions needed between 2 users to connect them.",
        default=1,
        validators=[MinValueValidator(1)],
    )
    minimum_degree = models.IntegerField(
        help_text="Minimum number of neighbors a node must have to be included.",
        default=2,
        validators=[MinValueValidator(1)],
    )
    minimum_community_size = models.IntegerField(
        help_text="Communities of users are removed if they contain too few " "elements",
        default=2,
        validators=[MinValueValidator(1)],
    )

    def __str__(self):
        return self.name


class TwitterDataCollection(DataCollection):
    min_mentions = models.IntegerField(
        help_text="Minimum number of times a user must be mentioned by the already collected users to be included.",
        default=0,
        validators=[MinValueValidator(0)],
    )
    max_days = models.IntegerField(
        help_text="Number of days max in the past when collecting a user timeline",
        default=20,
        validators=[MinValueValidator(0), MaxValueValidator(120)],
    )
    max_tweets = models.IntegerField(
        help_text="Maximal number of tweets collected from a user's timeline",
        default=200,
        validators=[MinValueValidator(1), MaxValueValidator(200)],
    )
    popular_tweets = models.IntegerField(
        help_text="Number of popular tweets (for lex. analysis) for each user",
        default=20,
        validators=[MinValueValidator(1), MaxValueValidator(1000)],
    )
    api_version = models.IntegerField(
        help_text="Twitter API version",
        default=1,
        validators=[MinValueValidator(1), MaxValueValidator(2)],
    )


class DataCollectionRun(models.Model):
    COLLECTION_STATUS = [
        ("stopped", "Stopped"),
        ("scheduled", "Scheduled"),
        ("running", "Running"),
        ("paused", "Paused"),
        ("completed", "Completed"),
        ("error", "Error"),
    ]
    id = models.UUIDField(primary_key=True, default=uuid.UUID("f8ed37e7-1a7f-474b-a3dc-35bbb39fa4e0"))

    def js_id(self):
        return str(self.id)[:8].replace("-", "_")

    def __str__(self):
        return str(self.id)

    collection = models.ForeignKey(DataCollection, on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)
    started = models.DateTimeField(default=timezone.now)
    finished = models.DateTimeField(default=timezone.now)
    status = models.CharField(
        max_length=25,
        choices=COLLECTION_STATUS,
        default="stopped",
        help_text="Collection status",
    )
    log = models.TextField(default="")
    chain = models.JSONField(null=False, default=dict)


class AbstractUser(models.Model):
    collection = models.ForeignKey(DataCollection, on_delete=models.CASCADE)
    name = models.CharField(max_length=250, help_text="Account/User name")

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class InitialNode(AbstractUser):
    class Meta:
        constraints = [models.UniqueConstraint(fields=["collection", "name"], name="unique initial node")]


class UserBlacklist(AbstractUser):
    pass

sadcollect/collect/forms.py
import json
from django import forms
from django.forms import ModelForm, Form
from django.forms import HiddenInput
from .models import DataCollection, TwitterDataCollection
from django_select2.forms import Select2Widget, Select2TagWidget


class DataCollectionFormUpdate(ModelForm):
    source = forms.CharField(widget=forms.TextInput(attrs={"readonly": "readonly"}))

    class Meta:
        model = DataCollection
        fields = (
            "name",
            "source",
            "depth",
            "sampling_probability",
            "collect_by",
            "max_nodes_per_hop",
        )


class TwitterConfigurationForm(ModelForm):
    class Meta:
        model = TwitterDataCollection
        fields = ("min_mentions", "max_days", "max_tweets", "popular_tweets")


class HashtagSearch(Form):
    hashtag = forms.CharField(max_length=50, min_length=3, widget=Select2Widget)


class UsersAdd(Form):
    def __init__(self, *args, **kwargs):
        users = kwargs.pop("users")
        super(UsersAdd, self).__init__(*args, **kwargs)
        self.fields["users_list"] = forms.MultipleChoiceField(widget=Select2TagWidget, choices=users, required=False)
        # pass the list of choices allowed as hidden input s.t. form can be validated as POST time
        self.fields["users_choices"] = forms.CharField(widget=HiddenInput(), initial=json.dumps(users))

sadcollect/templates/collect/_collect_table.html
<div class="dataTable_wrapper">
    <table id="data-collection-table" class="table table-sm table-bordered table-striped table-hover">
        <thead>
        <tr>
            <th class="text-center" scope="col">#</th>
            <th class="text-center" scope="col">Name</th>
            <th class="text-center" scope="col">Source</th>
            <th class="text-center" scope="col">Depth</th>
            <th class="text-center" scope="col">Sampling Proba. (%)</th>
            <th class="text-center" scope="col">Collect by</th>
            <th class="text-center" scope="col">Nb. initial nodes</th>
            <th class="text-center" scope="col">&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        {% for c in lst_collect %}
            <tr>
                <th class="text-center" scope="row">{{ forloop.counter }}</th>
                <td class="text-center">{{ c.name }}</td>
                <td class="text-center"><i class="fab fa-{{ c.source|lower }}"></i></td>
                <td class="text-center">{{ c.depth }}</td>
                <td class="text-center">{{ c.sampling_probability }}</td>
                <td class="text-center">{{ c.collect_by }}</td>
                <td class="text-center">{{ c.nb_nodes }}</td>
                <td class="text-center">
                    <!-- Start button -->
                    <span class="d-inline-block" tabindex="0"
                          data-toggle="tooltip" data-placement="top"
                          title="{% if c.nb_nodes < 1 %}Cannot start - no initial nodes found{% else %}Start{% endif %}">

                    <a type="button"
                       class="start-collect btn btn-sm btn-info {% if c.nb_nodes < 1 %}disabled{% endif %}"
                       href="{% url 'collect:start_collect' c.pk %}">
                        <span class="fa fa-play"></span>
                    </a>
                    </span>
                    <!-- Results button -->
                    <span class="d-inline-block" tabindex="0"
                          data-toggle="tooltip" data-placement="top"
                          title="{% if c.datacollectionrun_set.count == 0 %}No runs found{% else %}Show runs{% endif %}">

                    <a type="button"
                       class="collect-results btn btn-sm btn-info {% if c.datacollectionrun_set.count == 0 %}disabled{% endif %}"
                       href="{% url 'collect:list_runs' c.pk %}">
                        <span class="fa fa-poll-h"></span>
                    </a>
                    </span>
                    <!-- Update button -->
                    <span class="d-inline-block" tabindex="0"
                              data-toggle="tooltip" data-placement="top" title="Update collection parameters">
                        <a type="button" class="update-collect btn btn-sm btn-primary"
                                href="{% url 'collect:update_collect' c.pk %}">
                            <span class="fa fa-edit"></span>
                        </a>
                    </span>
                    <!--  Initial nodes button -->
                     <span class="d-inline-block" tabindex="0"
                                  data-toggle="tooltip" data-placement="top" title="Manage initial nodes">
                        <a class="initial-nodes-collect btn btn-sm btn-primary"
                           href="{% url 'collect:collect_start_nodes' c.pk %}">
                            <span class="fas fa-project-diagram"></span>
                        </a>
                     </span>
                    <!--  Blacklisted nodes button -->
                     <span class="d-inline-block" tabindex="0"
                                  data-toggle="tooltip" data-placement="top" title="Manage blacklist">
                        <a class="btn btn-sm btn-warning"
                           href="{% url 'collect:blacklist_nodes' c.pk %}">
                            <span class="fas fa-ban"></span>
                        </a>
                     </span>
                    <!-- Delete button -->
                 <span class="d-inline-block" tabindex="0"
                              data-toggle="tooltip" data-placement="top" title="Delete">
                    <a type="button" class="delete-collect btn btn-sm btn-danger"
                            href="{% url 'collect:delete_collect' c.pk %}">
                        <span class="fa fa-trash"></span>
                    </a>
                 </span>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

sadcollect/templates/collect/_nodes_table.html
<div class="dataTable_wrapper">
<table id="initial-nodes-table" class="table table-sm table-bordered table-striped table-hover">
  <thead>
  <tr>
    <th class="text-center" scope="col">#</th>
    <th class="text-center" scope="col">Name</th>
    <th class="text-center" scope="col">Update / Delete</th>
  </tr>
  </thead>
  <tbody>
  {% for c in lst_nodes %}
    <tr>
      <th class="text-center" scope="row">{{ forloop.counter }}</th>
      <td class="text-center">{{ c.name }}</td>
      <td class="text-center">
        <!-- Update button -->
        <a type="button" class="update-node btn btn-sm btn-primary"
           href="{% if mode == 'initial_nodes' %}
                    {% url 'collect:update_node' collect_id=collect_id pk=c.pk %}
                 {% else %}
                    {% url 'collect:update_blacklist_node' collect_id=collect_id pk=c.pk %}
                 {% endif %}">
          <span class="fa fa-edit"></span>
        </a>
        <!-- Delete button -->
        <a type="button" class="bs-modal delete-node btn btn-sm btn-danger"
           href="{% if mode == 'initial_nodes' %}
                    {% url 'collect:delete_node' collect_id=collect_id pk=c.pk %}
                 {% else %}
                    {% url 'collect:delete_blacklist_node' collect_id=collect_id pk=c.pk %}
                 {% endif %}">
          <span class="fa fa-trash"></span>
        </a>

      </td>
    </tr>
  {% endfor %}
  </tbody>
</table></div>

sadcollect/templates/collect/_runs_table.html
{% load collect_tags %}
<div class="dataTable_wrapper display nowrap">
    <table id="data-runs-table" class="table table-sm table-bordered table-striped table-hover">
        <thead>
        <tr>
            <th class="text-center" scope="col">#</th>
            <th class="text-center" scope="col">Status</th>
            <th class="text-center" scope="col">Log</th>
            <th class="text-center" scope="col">End date</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for c in datacollectruns %}

            <tr
                    {% if c.status == 'completed' %}
                    data-nodes="{{ c.graphmetadata.number_nodes }}"
                    data-edges="{{ c.graphmetadata.number_edges }}"
                    data-info="{{ c.graphmetadata.info|linebreaks }}"
                    {% endif %}
            >
                <td class="text-center">
                    {% if c.graphmetadata.name %}{{ c.graphmetadata.name }}<br/><small class="text-muted">{% endif %}{{ c.id }}{% if c.graphmetadata.name %}</small>{% endif %}
                    <!-- Rename button -->
                    <span class="d-inline-block float-right" tabindex="0"
                              data-toggle="tooltip" data-placement="top" title="Rename run">
                        <a type="button" class="btn btn-sm btn-primary"
                                href="{% url 'collect:rename_run' c.collection_id c.pk %}">
                            <span class="fa fa-edit"></span>
                        </a>
                    </span>
                </td>
                <td class="text-center">{{ c.status }}{% if c.status == 'running' %}
                    {% with lex_task=c.chain|get_item:'collect.tasks.extract_keywords' layout_task=c.chain|get_item:'collect.tasks.graph_layout_fa2' %}
                    <div class='progress-wrapper'>
                        <div id='progress-bar-{{ c.id }}' class='progress-bar' style="background-color: #68a9ef; width: 0%;">&nbsp;</div>
                    </div>
                    <div id="progress-bar-message-{{ c.id }}">&nbsp;</div>
                        {% if lex_task|length > 0 %}
                        <div class="progress-wrapper">
                            <div id='progress-bar-{{ lex_task }}' class='progress-bar' style="background-color: #68a9ef; width: 0%;">&nbsp;</div>
                        </div>
                        <div id="progress-bar-message-{{ lex_task }}">&nbsp;</div>
                        {% endif %}
                        {% if layout_task|length > 0 %}
                        <div class="progress-wrapper">
                            <div id='progress-bar-{{ layout_task }}' class='progress-bar' style="background-color: #68a9ef; width: 0%;">&nbsp;</div>
                        </div>
                        <div id="progress-bar-message-{{ layout_task }}">&nbsp;</div>
                        {% endif %}
                    {% endwith %}
                    {% endif %}
                </td>
                <td class="text-center" >
                  <a href="{% url 'collect:run_log' c.pk %}" class="btn-sm btn-info" type="button">
                    <i class="fas fa-file-alt"></i>
                  </a>
                </td>
                <td class="text-center" data-order="{{ c.finished.timestamp }}">{{ c.finished }}</td>
                <td class="text-center">
                    <a type="button" class="btn btn-sm btn-info {% if c.status != "completed" or c.graphmetadata.number_nodes == 0 %}disabled{% endif %}"
                            href="{% url 'viewer:display_graph' c.pk %}">
                        <span class="fas fa-binoculars"></span>
                    </a>
                 <span class="d-inline-block" tabindex="0"
                          data-toggle="tooltip" data-placement="top"
                          title="Edit annotations">

                    <a type="button" class="btn btn-sm btn-info {% if c.status != "completed" %}disabled{% endif %}"
                       href="{% url 'collect:annotate_run' c.collection_id c.pk %}">
                        <i class="fas fa-comment"></i>
                    </a>
                 </span>
                    <a type="button" class="delete-run btn btn-sm btn-danger"
                            href="{% url 'collect:delete_run' c.collection_id c.pk %}">
                        <span class="fa fa-trash"></span>
                    </a>
                </td>
                <td><i class="fas fa-plus-circle"></i></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

sadcollect/templates/collect/_tweets_table.html
{% load collect_tags %}
{% url 'collect:collect_start_nodes' collect_id as current_url %}
<div class="dataTable_wrapper">
    <table id="tweets-table" class="table table-sm table-bordered table-striped table-hover">
        <thead>
        <tr>
            <th class="text-center" scope="col">#</th>
            <th class="text-center" scope="col">User</th>
            <th class="text-center" scope="col">Text</th>
            <th class="text-center" scope="col"><i class="fas fa-heart"></i></th>
            <th class="text-center" scope="col"><i class="fas fa-retweet"></i></th>
        </tr>
        </thead>
        <tbody>
        {% for c in hashtag_data.statuses %}
            <tr>
                <th class="text-center" scope="row">{{ forloop.counter }}</th>
                <td>
                    <p class="text-center">
                        {{ c.user.screen_name }} {% if c.user.verified %}<i class="fas fa-check-circle"></i>{% endif %}
                        <button class="btn btn-link add-user" data-username="{{ c.user.screen_name }}"><i class="far fa-plus-square"></i></button>
                    </p>

                    <p><small>{{ c.user.followers_count|human_format }} <i class="fas fa-users"></i>
                        {{ c.user.favourites_count|human_format }} <i class="fas fa-heart"></i>
                        {{ c.user.created_at|to_date|date:"M Y" }}
                    </small></p>
                </td>
                <td><p>{{ c.text|hashtag_link:current_url }}</p>
                    <p><small>{{ c.created_at|to_date|date:"D j M Y" }}</small></p>
                </td>
                <td class="text-center">{{ c.favorite_count }}</td>
                <td class="text-center">{{ c.retweet_count }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

sadcollect/templates/collect/blacklisted_nodes.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags static %}
{% block custom_styles %}
    <link rel="stylesheet" href="{% static 'django_select2/django_select2.css' %}">
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    {% if lst_nodes %}
                        {% include 'collect/_nodes_table.html' %}
                    {% else %}
                        <p class="text-primary">No blacklisted nodes for current collection.</p>
                    {% endif %}
                    <div class="float-right">
                          <a href="{% url 'collect:home' %}" class="btn btn-info" type="button">
                              <i class="fas fa-arrow-left"></i> Back</a>
                          <a href="{% url 'collect:add_blacklist_node' collect_id %}" class="btn btn-primary ml-1"
                             type="button" id="add-node"><i class="fas fa-plus"></i> Create</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

sadcollect/templates/collect/hashtag.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Hashtags</h5>
                    <form>
                        <select id="select-hashtag"></select>
                        <button type="submit" class="btn btn-primary">Search</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Add user</h5>
                    <form>
                        <select id="select-users"></select>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                {% if hashtag_data %}
                    {% include 'collect/_tweets_table.html' %}
                {% else %}
                    <p class="text-primary">Empty data.</p>
                {% endif %}
            </div>
            <a href="{% url 'collect:home' %}" class="btn btn-primary float-right" type="button"><i
                    class="fas fa-arrow-left"></i> Back</a>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script type="text/javascript">

        $(document).ready(function () {
            let selectedValues = [];
            $('#tweets-table').DataTable({
                responsive: true, searching: false,
                columns: [null, null, {orderable: false}, null, null]
            });
            $('#select-hashtag').select2({
                data: {{ hashtags | safe}},
                theme: 'bootstrap4',
                tags: true
            });
            $('#select-users').select2({
                data: {{ mentions | safe }},
                multiple: true,
                theme: 'bootstrap4',
                tags: true
            })
            $('.add-user').click(function (e) {
                selectedValues.push($(this).data('username'));
                //console.log(selectedValues);
                $('#select-users').val(selectedValues).trigger('change');
            });

        });
    </script>
{% endblock %}

sadcollect/templates/collect/initial_nodes.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags static %}
{% block custom_styles %}
    <link rel="stylesheet" href="{% static 'django_select2/django_select2.css' %}">
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    {% if lst_nodes %}
                        {% include 'collect/_nodes_table.html' %}
                    {% else %}
                        <p class="text-primary">No initial nodes for current collection.</p>
                    {% endif %}
                    <div class="float-right">
                          <a href="{% url 'collect:home' %}" class="btn btn-info" type="button">
                              <i class="fas fa-arrow-left"></i> Back</a>
                          <a href="{% url 'collect:add_node' collect_id %}" class="btn btn-primary ml-1"
                             type="button" id="add-node"><i class="fas fa-plus"></i> Create</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Hashtag search</h5>
                    <form action="{% url 'collect:collect_start_nodes' collect_id %}" method="post">
                        {% csrf_token %}
                        {{ hashtag_form|crispy }}
                        <button type="submit" class="btn btn-primary">Search</button>
                    </form>
                </div>
            </div>
        </div>
    {% if has_mentions %}
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Add users</h5>
                    <form action="{% url 'collect:nodes_multi_add' collect_id hashtag %}" method="post">
                        {% csrf_token %}
                        {{ users_form|crispy }}
                        <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                </div>
            </div>
        </div>
    {% endif %}
    </div>
 {% if hashtag_data %}
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    {% include 'collect/_tweets_table.html' %}
                </div>
            </div>
        </div>
    </div>
 {% endif %}
{% endblock %}
{% block scripts %}
    <script type="text/javascript" src="{% static 'django_select2/django_select2.js' %}"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            let selectedValues = [];
            $('#initial-nodes-table').DataTable({
                responsive: true, searching: false,
                columns: [null, null, {orderable: false}]
            });
            $('#tweets-table').DataTable({
                responsive: true, searching: false,
                columns: [null, null, {orderable: false}, null, null]
            });
            $('#id_hashtag').djangoSelect2({
                data: {{ hashtags_select2 | safe}},
                theme: 'bootstrap4',
                tags: true,
                placeholder: {% if not has_hashtags %} 'enter hashtag...'{% else %} '{{ hashtag }}'{% endif %}
            });
            {% if has_mentions %}
            $('#id_users_list').djangoSelect2({
                data: {{ mentions_select2 | safe }},
                multiple: true,
                theme: 'bootstrap4',
                tags: true
            });
            $('.add-user').click(function (e) {
                selectedValues.push($(this).data('username'));
                //console.log(selectedValues);
                $('#id_users_list').val(selectedValues).trigger('change');
            });
            $('#id_users_list').on('select2:select', function (e) {
                const data = e.params.data;
                selectedValues.push(data.id);
            });
            // when order/page changes on the DT, re-wire click handlers
            $('#tweets-table').on('draw.dt', function(e){
                $('.add-user').off('click');
                $('.add-user').click(function (e) {
                    selectedValues.push($(this).data('username'));
                //console.log(selectedValues);
                    $('#id_users_list').val(selectedValues).trigger('change');
                });
            });
            {% endif %}


        });
    </script>
{% endblock %}