sadcollect/app/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("collect/", include("collect.urls")),
    path("viewer/", include("viewer.urls")),
    path("users/", include("users.urls")),
    path("", RedirectView.as_view(url="collect/", permanent=True)),
    path("select2/", include("django_select2.urls")),
    re_path(r"^celery-progress/", include("celery_progress.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sadcollect/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from rest_framework.authtoken import views as rest_views
from users.views import get_api_token

app_name = "users"
urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path("token/", get_api_token, name="get_api_token"),
    path("token-auth/", rest_views.obtain_auth_token),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

sadcollect/templates/_modal.html
<div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog mt-5">
    <div class="modal-content">
    </div>
  </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog mt-5" role="document">
    <div class="modal-content"></div>
  </div>
</div>

sadcollect/templates/base_generic.html
{% load active_link_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    {% block title %}<title>#SADcollect</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block base_styles %}
        <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static '@fortawesome/fontawesome-free/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}">
        <link rel="stylesheet" href="{% static 'datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}">
        <link rel="stylesheet" href="{% static 'select2/dist/css/select2.min.css' %}">
        <link rel="stylesheet" href="{% static '@ttskch/select2-bootstrap4-theme/dist/select2-bootstrap4.min.css' %}">
    {% endblock %}
    {% block custom_style %}
    {% endblock %}
    <!-- Add additional CSS in static file -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>


<div class="container-fluid d-flex h-100 flex-column">


    {% block navbar %}
        <div class="row">
            <div class="col-sm-4">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <a class="navbar-brand" href="#">#SAD</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarNavAltMarkup"
                            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                        <div class="navbar-nav">
                            {% if user.is_authenticated %}
                                {% comment %}
                                <a class="nav-item nav-link {% active_link 'dashboard:home' %}"
                                   href="{% url 'dashboard:home' %}">Home</a>
                                {% endcomment %}
                                <a class="nav-item nav-link {% active_link 'collect:home' %}"
                                   href="{% url 'collect:home' %}">Data collection</a>
                                <a class="nav-item nav-link {% active_link 'viewer:home' %}"
                                   href="{% url 'viewer:home' %}">Viewer</a>
                            {% else %}
                                <a class="nav-item nav-link active"
                                   href="{% url 'users:login' %}?next={{ request.path }}">
                                    <i class="fas fa-sign-in-alt"></i> Login</a>
                            {% endif %}
                        </div>
                    </div>
                </nav>
            </div>
            <div class="col-sm-6">

            </div>
            <div class="col-sm-2">
                {% if user.is_authenticated %}
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuUser"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.get_full_name }} ({{ user.get_username }})
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuUser">
                            <a class="dropdown-item" href="{% url 'users:get_api_token' %}">API token <i
                                    class="fas fa-key"></i></a>
                            <a class="dropdown-item" href="{% url 'users:logout' %}">Logout <i
                                    class="fas fa-sign-out-alt"></i></a>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    {% endblock %}

    {% if messages %}
        <div class="row justify-content-center">
            <div class="col-sm-7">
                {% for message in messages %}
                    <div class="alert {{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
    {% block content_start %}
        <div class="row justify-content-center">
        <div class="col-sm-10 ">
    {% endblock %}
    {% block content %}{% endblock %}

    {% block pagination %}
        {% if is_paginated %}
            <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
            </div>
        {% endif %}
    {% endblock %}

    {% block content_end %}
        </div>
        </div>
    {% endblock %}
</div>
</body>
{% block base_scripts %}
    <script type="text/javascript" src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript"
            src="{% static 'datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script type="text/javascript"
            src="{% static 'datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'select2/dist/js/select2.min.js' %}"></script>
{% endblock %}
{% block scripts %}{% endblock %}
</html>

sadcollect/templates/delete.html
{% extends 'base_generic.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        <div class="card">
            <div class="card-header">
                {{ title }}
            </div>
            <div class="card-body">
                <div class="alert alert-danger">
                    Are you sure you want to delete this {{ item }} ?
                </div>
            </div>
        </div>
        <span class="float-right">
            <a href="{{ view.get_success_url }}" class=" btn btn-info">
                <i class="fas fa-arrow-left"></i>
                Cancel
            </a>
            <button type="submit" id="delete-btn" class="btn btn-danger">Delete</button>
        </span>
    </form>
{% endblock %}

sadcollect/templates/edit.html
{% extends 'base_generic.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form method="post" action="">
    {% csrf_token %}
    {% crispy form %}
    <span class="float-right">
        <a href="{{ view.get_success_url }}" class=" btn btn-info">
            <i class="fas fa-arrow-left"></i>
            Cancel
        </a>
        <button type="submit" class="submit-btn btn btn-primary">{{ action }}</button>
    </span>
</form>
{% endblock %}